"""added relationship between user and comment

Revision ID: 2dc3a426d4d4
Revises: 1605b72f71b5
Create Date: 2017-09-22 12:31:29.017428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc3a426d4d4'
down_revision = '1605b72f71b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
