"""empty message

Revision ID: 9dc59736b321
Revises: b3a77a700631
Create Date: 2017-09-21 15:10:09.329418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc59736b321'
down_revision = 'b3a77a700631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'slug')
    # ### end Alembic commands ###
