"""add thumbnai col for image

Revision ID: b2d64491db5e
Revises: 480ecaa80c36
Create Date: 2017-10-10 09:37:39.572916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d64491db5e'
down_revision = '480ecaa80c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('thumbnail_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'thumbnail_name')
    # ### end Alembic commands ###
